---
# handlers file for CentOS7-CIS

- name: restart auditd
  become: yes
  service:
    name: auditd
    state: restarted

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted

- name: restart syslog-ng
  become: yes
  service:
    name: syslog-ng
    state: restarted

- name: sysctl flush ipv4 route table
  become: yes
  sysctl:
    name: net.ipv4.route.flush
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ansible_virtualization_type != "docker"

- name: sysctl flush ipv6 route table
  become: yes
  sysctl:
    name: net.ipv6.route.flush
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ansible_virtualization_type != "docker"

- name: systemd restart tmp.mount
  become: yes
  systemd:
    name: tmp.mount
    daemon_reload: yes
    enabled: yes
    masked: no
    state: reloaded

- name: generate new grub config
  become: yes
  shell: grub2-mkconfig -o {{ grub_cfg.stat.lnk_source }}

- name: restart xinetd
  become: yes
  service:
    name: xinetd
    state: restarted

- name: systemctl restart postfix
  become: yes
  service:
    name: postfix
    state: restarted

#- name: restart sshd
#  debug:
#      msg: "checking /etc/ssh/sshd_config first"
#  changed_when: true
#  notify:
#      - generate host keys
#      - check sshd configuration
#      - restart sshd - after config check

#- name: generate host keys
#  command: '/usr/bin/ssh-keygen -A'
#  register: ssh_host_keys

#- name: check sshd configuration
#  command: '/usr/sbin/sshd -t'
#  register: sshd_config
#  changed_when: "sshd_config.rc != 0"

- name: restart sshd
  service:
      name: sshd
      state: restarted
  ignore_errors: True

